version: '3.8'

services:
  db:
    image: postgres
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@example.com
     PGADMIN_DEFAULT_PASSWORD: admin
   ports:
    - "5050:80"


